/* 
 * Beaconcha.in ETH2 API
 *
 * High performance API for querying information from the Ethereum 2.0 beacon chain The API is currently free to use. A fair use policy applies. Calls are rate limited to 10 requests / 1 minute / IP. All API results are cached for 1 minute. If you required a higher usage plan please checkout https://beaconcha.in/pricing.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBlockApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get the attestations included in a specific block
        /// </summary>
        /// <remarks>
        /// Returns the attestations included in a specific block
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>string</returns>
        string ApiV1BlockSlotAttestationsGet (string slot);

        /// <summary>
        /// Get the attestations included in a specific block
        /// </summary>
        /// <remarks>
        /// Returns the attestations included in a specific block
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> ApiV1BlockSlotAttestationsGetWithHttpInfo (string slot);
        /// <summary>
        /// Get the attester slashings included in a specific block
        /// </summary>
        /// <remarks>
        /// Returns the attester slashings included in a specific block
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>string</returns>
        string ApiV1BlockSlotAttesterslashingsGet (string slot);

        /// <summary>
        /// Get the attester slashings included in a specific block
        /// </summary>
        /// <remarks>
        /// Returns the attester slashings included in a specific block
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> ApiV1BlockSlotAttesterslashingsGetWithHttpInfo (string slot);
        /// <summary>
        /// Get the deposits included in a specific block
        /// </summary>
        /// <remarks>
        /// Returns the deposits included in a specific block
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>string</returns>
        string ApiV1BlockSlotDepositsGet (string slot);

        /// <summary>
        /// Get the deposits included in a specific block
        /// </summary>
        /// <remarks>
        /// Returns the deposits included in a specific block
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> ApiV1BlockSlotDepositsGetWithHttpInfo (string slot);
        /// <summary>
        /// Get block
        /// </summary>
        /// <remarks>
        /// Returns a block by its slot or root hash
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slotOrHash">Block slot or root hash or the string latest</param>
        /// <returns>string</returns>
        string ApiV1BlockSlotOrHashGet (string slotOrHash);

        /// <summary>
        /// Get block
        /// </summary>
        /// <remarks>
        /// Returns a block by its slot or root hash
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slotOrHash">Block slot or root hash or the string latest</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> ApiV1BlockSlotOrHashGetWithHttpInfo (string slotOrHash);
        /// <summary>
        /// Get the proposer slashings included in a specific block
        /// </summary>
        /// <remarks>
        /// Returns the proposer slashings included in a specific block
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>string</returns>
        string ApiV1BlockSlotProposerslashingsGet (string slot);

        /// <summary>
        /// Get the proposer slashings included in a specific block
        /// </summary>
        /// <remarks>
        /// Returns the proposer slashings included in a specific block
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> ApiV1BlockSlotProposerslashingsGetWithHttpInfo (string slot);
        /// <summary>
        /// Get the voluntary exits included in a specific block
        /// </summary>
        /// <remarks>
        /// Returns the voluntary exits included in a specific block
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>string</returns>
        string ApiV1BlockSlotVoluntaryexitsGet (string slot);

        /// <summary>
        /// Get the voluntary exits included in a specific block
        /// </summary>
        /// <remarks>
        /// Returns the voluntary exits included in a specific block
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> ApiV1BlockSlotVoluntaryexitsGetWithHttpInfo (string slot);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get the attestations included in a specific block
        /// </summary>
        /// <remarks>
        /// Returns the attestations included in a specific block
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> ApiV1BlockSlotAttestationsGetAsync (string slot);

        /// <summary>
        /// Get the attestations included in a specific block
        /// </summary>
        /// <remarks>
        /// Returns the attestations included in a specific block
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> ApiV1BlockSlotAttestationsGetAsyncWithHttpInfo (string slot);
        /// <summary>
        /// Get the attester slashings included in a specific block
        /// </summary>
        /// <remarks>
        /// Returns the attester slashings included in a specific block
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> ApiV1BlockSlotAttesterslashingsGetAsync (string slot);

        /// <summary>
        /// Get the attester slashings included in a specific block
        /// </summary>
        /// <remarks>
        /// Returns the attester slashings included in a specific block
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> ApiV1BlockSlotAttesterslashingsGetAsyncWithHttpInfo (string slot);
        /// <summary>
        /// Get the deposits included in a specific block
        /// </summary>
        /// <remarks>
        /// Returns the deposits included in a specific block
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> ApiV1BlockSlotDepositsGetAsync (string slot);

        /// <summary>
        /// Get the deposits included in a specific block
        /// </summary>
        /// <remarks>
        /// Returns the deposits included in a specific block
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> ApiV1BlockSlotDepositsGetAsyncWithHttpInfo (string slot);
        /// <summary>
        /// Get block
        /// </summary>
        /// <remarks>
        /// Returns a block by its slot or root hash
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slotOrHash">Block slot or root hash or the string latest</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> ApiV1BlockSlotOrHashGetAsync (string slotOrHash);

        /// <summary>
        /// Get block
        /// </summary>
        /// <remarks>
        /// Returns a block by its slot or root hash
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slotOrHash">Block slot or root hash or the string latest</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> ApiV1BlockSlotOrHashGetAsyncWithHttpInfo (string slotOrHash);
        /// <summary>
        /// Get the proposer slashings included in a specific block
        /// </summary>
        /// <remarks>
        /// Returns the proposer slashings included in a specific block
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> ApiV1BlockSlotProposerslashingsGetAsync (string slot);

        /// <summary>
        /// Get the proposer slashings included in a specific block
        /// </summary>
        /// <remarks>
        /// Returns the proposer slashings included in a specific block
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> ApiV1BlockSlotProposerslashingsGetAsyncWithHttpInfo (string slot);
        /// <summary>
        /// Get the voluntary exits included in a specific block
        /// </summary>
        /// <remarks>
        /// Returns the voluntary exits included in a specific block
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> ApiV1BlockSlotVoluntaryexitsGetAsync (string slot);

        /// <summary>
        /// Get the voluntary exits included in a specific block
        /// </summary>
        /// <remarks>
        /// Returns the voluntary exits included in a specific block
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> ApiV1BlockSlotVoluntaryexitsGetAsyncWithHttpInfo (string slot);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class BlockApi : IBlockApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="BlockApi"/> class.
        /// </summary>
        /// <returns></returns>
        public BlockApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BlockApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public BlockApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get the attestations included in a specific block Returns the attestations included in a specific block
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>string</returns>
        public string ApiV1BlockSlotAttestationsGet (string slot)
        {
             ApiResponse<string> localVarResponse = ApiV1BlockSlotAttestationsGetWithHttpInfo(slot);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get the attestations included in a specific block Returns the attestations included in a specific block
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse< string > ApiV1BlockSlotAttestationsGetWithHttpInfo (string slot)
        {
            // verify the required parameter 'slot' is set
            if (slot == null)
                throw new ApiException(400, "Missing required parameter 'slot' when calling BlockApi->ApiV1BlockSlotAttestationsGet");

            var localVarPath = "/api/v1/block/{slot}/attestations";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (slot != null) localVarPathParams.Add("slot", this.Configuration.ApiClient.ParameterToString(slot)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1BlockSlotAttestationsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Get the attestations included in a specific block Returns the attestations included in a specific block
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> ApiV1BlockSlotAttestationsGetAsync (string slot)
        {
             ApiResponse<string> localVarResponse = await ApiV1BlockSlotAttestationsGetAsyncWithHttpInfo(slot);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get the attestations included in a specific block Returns the attestations included in a specific block
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> ApiV1BlockSlotAttestationsGetAsyncWithHttpInfo (string slot)
        {
            // verify the required parameter 'slot' is set
            if (slot == null)
                throw new ApiException(400, "Missing required parameter 'slot' when calling BlockApi->ApiV1BlockSlotAttestationsGet");

            var localVarPath = "/api/v1/block/{slot}/attestations";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (slot != null) localVarPathParams.Add("slot", this.Configuration.ApiClient.ParameterToString(slot)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1BlockSlotAttestationsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Get the attester slashings included in a specific block Returns the attester slashings included in a specific block
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>string</returns>
        public string ApiV1BlockSlotAttesterslashingsGet (string slot)
        {
             ApiResponse<string> localVarResponse = ApiV1BlockSlotAttesterslashingsGetWithHttpInfo(slot);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get the attester slashings included in a specific block Returns the attester slashings included in a specific block
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse< string > ApiV1BlockSlotAttesterslashingsGetWithHttpInfo (string slot)
        {
            // verify the required parameter 'slot' is set
            if (slot == null)
                throw new ApiException(400, "Missing required parameter 'slot' when calling BlockApi->ApiV1BlockSlotAttesterslashingsGet");

            var localVarPath = "/api/v1/block/{slot}/attesterslashings";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (slot != null) localVarPathParams.Add("slot", this.Configuration.ApiClient.ParameterToString(slot)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1BlockSlotAttesterslashingsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Get the attester slashings included in a specific block Returns the attester slashings included in a specific block
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> ApiV1BlockSlotAttesterslashingsGetAsync (string slot)
        {
             ApiResponse<string> localVarResponse = await ApiV1BlockSlotAttesterslashingsGetAsyncWithHttpInfo(slot);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get the attester slashings included in a specific block Returns the attester slashings included in a specific block
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> ApiV1BlockSlotAttesterslashingsGetAsyncWithHttpInfo (string slot)
        {
            // verify the required parameter 'slot' is set
            if (slot == null)
                throw new ApiException(400, "Missing required parameter 'slot' when calling BlockApi->ApiV1BlockSlotAttesterslashingsGet");

            var localVarPath = "/api/v1/block/{slot}/attesterslashings";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (slot != null) localVarPathParams.Add("slot", this.Configuration.ApiClient.ParameterToString(slot)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1BlockSlotAttesterslashingsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Get the deposits included in a specific block Returns the deposits included in a specific block
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>string</returns>
        public string ApiV1BlockSlotDepositsGet (string slot)
        {
             ApiResponse<string> localVarResponse = ApiV1BlockSlotDepositsGetWithHttpInfo(slot);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get the deposits included in a specific block Returns the deposits included in a specific block
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse< string > ApiV1BlockSlotDepositsGetWithHttpInfo (string slot)
        {
            // verify the required parameter 'slot' is set
            if (slot == null)
                throw new ApiException(400, "Missing required parameter 'slot' when calling BlockApi->ApiV1BlockSlotDepositsGet");

            var localVarPath = "/api/v1/block/{slot}/deposits";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (slot != null) localVarPathParams.Add("slot", this.Configuration.ApiClient.ParameterToString(slot)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1BlockSlotDepositsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Get the deposits included in a specific block Returns the deposits included in a specific block
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> ApiV1BlockSlotDepositsGetAsync (string slot)
        {
             ApiResponse<string> localVarResponse = await ApiV1BlockSlotDepositsGetAsyncWithHttpInfo(slot);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get the deposits included in a specific block Returns the deposits included in a specific block
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> ApiV1BlockSlotDepositsGetAsyncWithHttpInfo (string slot)
        {
            // verify the required parameter 'slot' is set
            if (slot == null)
                throw new ApiException(400, "Missing required parameter 'slot' when calling BlockApi->ApiV1BlockSlotDepositsGet");

            var localVarPath = "/api/v1/block/{slot}/deposits";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (slot != null) localVarPathParams.Add("slot", this.Configuration.ApiClient.ParameterToString(slot)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1BlockSlotDepositsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Get block Returns a block by its slot or root hash
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slotOrHash">Block slot or root hash or the string latest</param>
        /// <returns>string</returns>
        public string ApiV1BlockSlotOrHashGet (string slotOrHash)
        {
             ApiResponse<string> localVarResponse = ApiV1BlockSlotOrHashGetWithHttpInfo(slotOrHash);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get block Returns a block by its slot or root hash
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slotOrHash">Block slot or root hash or the string latest</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse< string > ApiV1BlockSlotOrHashGetWithHttpInfo (string slotOrHash)
        {
            // verify the required parameter 'slotOrHash' is set
            if (slotOrHash == null)
                throw new ApiException(400, "Missing required parameter 'slotOrHash' when calling BlockApi->ApiV1BlockSlotOrHashGet");

            var localVarPath = "/api/v1/block/{slotOrHash}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (slotOrHash != null) localVarPathParams.Add("slotOrHash", this.Configuration.ApiClient.ParameterToString(slotOrHash)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1BlockSlotOrHashGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Get block Returns a block by its slot or root hash
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slotOrHash">Block slot or root hash or the string latest</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> ApiV1BlockSlotOrHashGetAsync (string slotOrHash)
        {
             ApiResponse<string> localVarResponse = await ApiV1BlockSlotOrHashGetAsyncWithHttpInfo(slotOrHash);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get block Returns a block by its slot or root hash
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slotOrHash">Block slot or root hash or the string latest</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> ApiV1BlockSlotOrHashGetAsyncWithHttpInfo (string slotOrHash)
        {
            // verify the required parameter 'slotOrHash' is set
            if (slotOrHash == null)
                throw new ApiException(400, "Missing required parameter 'slotOrHash' when calling BlockApi->ApiV1BlockSlotOrHashGet");

            var localVarPath = "/api/v1/block/{slotOrHash}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (slotOrHash != null) localVarPathParams.Add("slotOrHash", this.Configuration.ApiClient.ParameterToString(slotOrHash)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1BlockSlotOrHashGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Get the proposer slashings included in a specific block Returns the proposer slashings included in a specific block
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>string</returns>
        public string ApiV1BlockSlotProposerslashingsGet (string slot)
        {
             ApiResponse<string> localVarResponse = ApiV1BlockSlotProposerslashingsGetWithHttpInfo(slot);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get the proposer slashings included in a specific block Returns the proposer slashings included in a specific block
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse< string > ApiV1BlockSlotProposerslashingsGetWithHttpInfo (string slot)
        {
            // verify the required parameter 'slot' is set
            if (slot == null)
                throw new ApiException(400, "Missing required parameter 'slot' when calling BlockApi->ApiV1BlockSlotProposerslashingsGet");

            var localVarPath = "/api/v1/block/{slot}/proposerslashings";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (slot != null) localVarPathParams.Add("slot", this.Configuration.ApiClient.ParameterToString(slot)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1BlockSlotProposerslashingsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Get the proposer slashings included in a specific block Returns the proposer slashings included in a specific block
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> ApiV1BlockSlotProposerslashingsGetAsync (string slot)
        {
             ApiResponse<string> localVarResponse = await ApiV1BlockSlotProposerslashingsGetAsyncWithHttpInfo(slot);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get the proposer slashings included in a specific block Returns the proposer slashings included in a specific block
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> ApiV1BlockSlotProposerslashingsGetAsyncWithHttpInfo (string slot)
        {
            // verify the required parameter 'slot' is set
            if (slot == null)
                throw new ApiException(400, "Missing required parameter 'slot' when calling BlockApi->ApiV1BlockSlotProposerslashingsGet");

            var localVarPath = "/api/v1/block/{slot}/proposerslashings";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (slot != null) localVarPathParams.Add("slot", this.Configuration.ApiClient.ParameterToString(slot)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1BlockSlotProposerslashingsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Get the voluntary exits included in a specific block Returns the voluntary exits included in a specific block
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>string</returns>
        public string ApiV1BlockSlotVoluntaryexitsGet (string slot)
        {
             ApiResponse<string> localVarResponse = ApiV1BlockSlotVoluntaryexitsGetWithHttpInfo(slot);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get the voluntary exits included in a specific block Returns the voluntary exits included in a specific block
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse< string > ApiV1BlockSlotVoluntaryexitsGetWithHttpInfo (string slot)
        {
            // verify the required parameter 'slot' is set
            if (slot == null)
                throw new ApiException(400, "Missing required parameter 'slot' when calling BlockApi->ApiV1BlockSlotVoluntaryexitsGet");

            var localVarPath = "/api/v1/block/{slot}/voluntaryexits";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (slot != null) localVarPathParams.Add("slot", this.Configuration.ApiClient.ParameterToString(slot)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1BlockSlotVoluntaryexitsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Get the voluntary exits included in a specific block Returns the voluntary exits included in a specific block
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> ApiV1BlockSlotVoluntaryexitsGetAsync (string slot)
        {
             ApiResponse<string> localVarResponse = await ApiV1BlockSlotVoluntaryexitsGetAsyncWithHttpInfo(slot);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get the voluntary exits included in a specific block Returns the voluntary exits included in a specific block
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="slot">Block slot</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> ApiV1BlockSlotVoluntaryexitsGetAsyncWithHttpInfo (string slot)
        {
            // verify the required parameter 'slot' is set
            if (slot == null)
                throw new ApiException(400, "Missing required parameter 'slot' when calling BlockApi->ApiV1BlockSlotVoluntaryexitsGet");

            var localVarPath = "/api/v1/block/{slot}/voluntaryexits";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (slot != null) localVarPathParams.Add("slot", this.Configuration.ApiClient.ParameterToString(slot)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1BlockSlotVoluntaryexitsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

    }
}
