/*
 * Beaconcha.in ETH2 API
 * High performance API for querying information from the Ethereum 2.0 beacon chain The API is currently free to use. A fair use policy applies. Calls are rate limited to 10 requests / 1 minute / IP. All API results are cached for 1 minute. If you required a higher usage plan please checkout https://beaconcha.in/pricing.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.prototyping.validatormonitor.integration.beaconchain.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse2001
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-12-12T13:45:51.285Z")



public class InlineResponse2001 {
  @SerializedName("data")
  private List<TypesMinimalTaggedValidators> data = null;

  @SerializedName("types.ApiResponse")
  private TypesApiResponse typesApiResponse = null;

  public InlineResponse2001 data(List<TypesMinimalTaggedValidators> data) {
    this.data = data;
    return this;
  }

  public InlineResponse2001 addDataItem(TypesMinimalTaggedValidators dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<TypesMinimalTaggedValidators>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(value = "")
  public List<TypesMinimalTaggedValidators> getData() {
    return data;
  }

  public void setData(List<TypesMinimalTaggedValidators> data) {
    this.data = data;
  }

  public InlineResponse2001 typesApiResponse(TypesApiResponse typesApiResponse) {
    this.typesApiResponse = typesApiResponse;
    return this;
  }

   /**
   * Get typesApiResponse
   * @return typesApiResponse
  **/
  @ApiModelProperty(value = "")
  public TypesApiResponse getTypesApiResponse() {
    return typesApiResponse;
  }

  public void setTypesApiResponse(TypesApiResponse typesApiResponse) {
    this.typesApiResponse = typesApiResponse;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001 inlineResponse2001 = (InlineResponse2001) o;
    return Objects.equals(this.data, inlineResponse2001.data) &&
        Objects.equals(this.typesApiResponse, inlineResponse2001.typesApiResponse);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, typesApiResponse);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001 {\n");
    
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    typesApiResponse: ").append(toIndentedString(typesApiResponse)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

