/*
 * Beaconcha.in ETH2 API
 * High performance API for querying information from the Ethereum 2.0 beacon chain The API is currently free to use. A fair use policy applies. Calls are rate limited to 10 requests / 1 minute / IP. All API results are cached for 1 minute. If you required a higher usage plan please checkout https://beaconcha.in/pricing.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.prototyping.validatormonitor.integration.beaconchain.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * TypesMinimalTaggedValidators
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-12-12T13:45:51.285Z")



public class TypesMinimalTaggedValidators {
  @SerializedName("index")
  private Integer index = null;

  @SerializedName("pubKey")
  private String pubKey = null;

  public TypesMinimalTaggedValidators index(Integer index) {
    this.index = index;
    return this;
  }

   /**
   * Get index
   * @return index
  **/
  @ApiModelProperty(value = "")
  public Integer getIndex() {
    return index;
  }

  public void setIndex(Integer index) {
    this.index = index;
  }

  public TypesMinimalTaggedValidators pubKey(String pubKey) {
    this.pubKey = pubKey;
    return this;
  }

   /**
   * Get pubKey
   * @return pubKey
  **/
  @ApiModelProperty(value = "")
  public String getPubKey() {
    return pubKey;
  }

  public void setPubKey(String pubKey) {
    this.pubKey = pubKey;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TypesMinimalTaggedValidators typesMinimalTaggedValidators = (TypesMinimalTaggedValidators) o;
    return Objects.equals(this.index, typesMinimalTaggedValidators.index) &&
        Objects.equals(this.pubKey, typesMinimalTaggedValidators.pubKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(index, pubKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TypesMinimalTaggedValidators {\n");
    
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    pubKey: ").append(toIndentedString(pubKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

